---

- name: Apply bash aliases/functions
  bodsch.core.bash_aliases:
    state: present
    backup: true
    users: "{{ bash_alias_users }}"
    common_aliases: "{{ bash_alias_common_aliases | default([]) }}"
    common_functions: "{{ bash_alias_common_functions | default([]) }}"

...
