---

bash_alias_common_aliases:
  - alias: ll
    command: "ls -lah"
  - alias: "myip"
    command: "curl --silent ifconfig.me"
  - alias: scs
    command: "systemctl status"

bash_alias_users:
  - name: alice
    aliases:
      - alias: foo
        command: "echo 'foo'"
    functions:
      - name: mkcd
        content: |
          mkdir -p "$1" && cd "$1"
  - name: bob
    aliases: []
    functions: []
  # - name: carol
  # - name: dave
  # - name: erin
  # - name: frank
  # - name: grace
  # - name: heidi
  # - name: ivan
  # - name: judy

...
