
namespace: bodsch
name: core

version: 1.0.15

readme: README.md

authors:
  - Bodo Schulz <bodo@boone-schulz.de>

description: collection of core modules for my ansible roles

license:
  - Apache-2.0

license_file: ''

tags: []

dependencies: {}

repository: https://github.com/bodsch/ansible-collection-core
documentation: https://github.com/bodsch/ansible-collection-core/README.md
homepage: https://github.com/bodsch/ansible-collection-core
issues: https://github.com/bodsch/ansible-collection-core/issues

build_ignore:
  - "galaxy.yml"
  - "*.pyc"
  - "*.retry"
  - ".ansible-lint"
  - ".editorconfig"
  - ".flake8"
  - ".gitignore"
  - ".yamllint"
  - ".github"
