---

pacman_config:
  architecture: auto
  color: true
  verbose_pkg_lists: true
  parallel_downloads: 2
  no_progress_bar: false

pacman_repositories:
  custom:
    enabled: false
    sig_level:
      - Optional
      - TrustAll
    server: file:///home/custompkgs
    usage:
      - All

  core:
    enabled: true
    include: /etc/pacman.d/mirrorlist

  extra:
    enabled: true
    include: /etc/pacman.d/mirrorlist

  community-testing:
    enabled: false
    include: /etc/pacman.d/mirrorlist

  community:
    enabled: false
    include: /etc/pacman.d/mirrorlist

pacman_mirrors:
  "Default mirrors":
    enabled: true
    servers:
      - https://geo.mirror.pkgbuild.com/$repo/os/$arch
      - https://mirror.rackspace.com/archlinux/$repo/os/$arch
      - https://mirror.leaseweb.net/archlinux/$repo/os/$arch

...
