---

sshd_packages:
  - openssh-server
  - openssh-sftp-server

sshd_sftp_server: /usr/lib/openssh/sftp-server
sshd_service: sshd
sshd_binary: /usr/sbin/sshd

sshd_hostkeys_nofips: []

sshd_defaults_config:
  port:
    - 22
  address_family: any
  listen_address:
    - "0.0.0.0"
  HostKey:
    - /etc/ssh/ssh_host_rsa_key
    - /etc/ssh/ssh_host_ecdsa_key
    - /etc/ssh/ssh_host_ed25519_key
  RekeyLimit:
    - default
    - none
  SyslogFacility: AUTH
  LogLevel: INFO
  LoginGraceTime: 2m
  PermitRootLogin: prohibit-password
  StrictModes: yes
  MaxAuthTries: 6
  MaxSessions: 10
  PubkeyAuthentication: yes

  # Expect .ssh/authorized_keys2 to be disregarded by default in future.
  AuthorizedKeysFile:
    - .ssh/authorized_keys

  AuthorizedPrincipalsFile: none

  AuthorizedKeysCommand: none
  AuthorizedKeysCommandUser: nobody

  # For this to work you will also need host keys in /etc/ssh/ssh_known_hosts
  HostbasedAuthentication: no
  # Change to yes if you don't trust ~/.ssh/known_hosts for
  # HostbasedAuthentication
  IgnoreUserKnownHosts: no
  # Don't read the user's ~/.rhosts and ~/.shosts files
  IgnoreRhosts: yes

  # To disable tunneled clear text passwords, change to no here!
  PasswordAuthentication: yes
  PermitEmptyPasswords: no

  # Change to yes to enable challenge-response passwords (beware issues with
  # some PAM modules and threads)
  ChallengeResponseAuthentication: no

  # Kerberos options
  KerberosAuthentication: no
  KerberosOrLocalPasswd: yes
  KerberosTicketCleanup: yes
  KerberosGetAFSToken: no

  # GSSAPI options
  GSSAPIAuthentication: no
  GSSAPICleanupCredentials: yes
  GSSAPIStrictAcceptorCheck: yes
  GSSAPIKeyExchange: no

  # Set this to 'yes' to enable PAM authentication, account processing,
  # and session processing. If this is enabled, PAM authentication will
  # be allowed through the ChallengeResponseAuthentication and
  # PasswordAuthentication.  Depending on your PAM configuration,
  # PAM authentication via ChallengeResponseAuthentication may bypass
  # the setting of "PermitRootLogin without-password".
  # If you just want the PAM account and session checks to run without
  # PAM authentication, then enable this but set PasswordAuthentication
  # and ChallengeResponseAuthentication to 'no'.
  UsePAM: yes

  AllowAgentForwarding: yes
  AllowTcpForwarding: yes
  GatewayPorts: no
  X11Forwarding: no
  X11DisplayOffset: 10
  X11UseLocalhost: yes
  PermitTTY: yes
  PrintMotd: no
  PrintLastLog: yes
  TCPKeepAlive: yes
  PermitUserEnvironment: no
  Compression: delayed
  ClientAliveInterval: 0
  ClientAliveCountMax: 3
  UseDNS: no
  PidFile: /var/run/sshd.pid
  MaxStartups: 10:30:100
  PermitTunnel: no
  ChrootDirectory: none
  VersionAddendum: none

  # no default banner path
  Banner: none

  # Allow client to pass locale environment variables
  AcceptEnv:
    - LANG
    - LC_*

  # override default of no subsystems
  Subsystem:
    - name: sftp
      path: /usr/lib/openssh/sftp-server

  # Example of overriding settings on a per-user basis
  Match_User:
    - username: anoncvs
      options:
        - X11Forwarding: no
        - AllowTcpForwarding: no
        - PermitTTY: no
        - ForceCommand:
            - cvs
            - server

ssh_defaults_config:
  - host: "*"
    # ForwardAgent: false
    # ForwardX11: false
    # ForwardX11Trusted: false
    # PasswordAuthentication: true
    # HostbasedAuthentication: ""
    # GSSAPIAuthentication: ""
    # GSSAPIDelegateCredentials: ""
    # GSSAPIKeyExchange: false
    # GSSAPITrustDNS: false
    # BatchMode: false
    # CheckHostIP: true
    # AddressFamily: any
    # ConnectTimeout: 0
    # StrictHostKeyChecking: ask
    # IdentityFile:
    #   - "~/.ssh/id_rsa"
    #   - "~/.ssh/id_dsa"
    #   - "~/.ssh/id_ecdsa"
    #   - "~/.ssh/id_ed25519"
    # Port: 22
    # Ciphers:
    #   - aes128-ctr
    #   - aes192-ctr
    #   - aes256-ctr
    #   - aes128-cbc
    #   - 3des-cbc
    # MACs:
    #   - hmac-md5
    #   - hmac-sha1
    #   - umac-64@openssh.com
    # EscapeChar: "~"
    # Tunnel: false
    # TunnelDevice: "any:any"
    # PermitLocalCommand: false
    # VisualHostKey: false
    # ProxyCommand: ssh -q -W %h:%p gateway.example.com
    # RekeyLimit: 1G 1h
    # UserKnownHostsFile: ~/.ssh/known_hosts.d/%k
    SendEnv:
      - "LANG LC_*"
    HashKnownHosts: true

...
