---

sshd_packages:
  - openssh-server
  - openssh-sftp-server

sshd_sftp_server: /usr/lib/openssh/sftp-server
sshd_service: sshd
sshd_binary: /usr/sbin/sshd

sshd_hostkeys_nofips: []

sshd_defaults_config:
  port: []
  #  - 22
  address_family: any
  listen_address:
    - "0.0.0.0:22"
  host_keys:
    - /etc/ssh/ssh_host_rsa_key
    - /etc/ssh/ssh_host_ecdsa_key
    - /etc/ssh/ssh_host_ed25519_key
  rekey_limit:
    - default
    - none
  syslog_facility: AUTH
  log_level: INFO
  login_grace_time: 2m
  permit_root_login: prohibit-password
  strict_modes: yes
  max_auth_tries: 6
  max_sessions: 10
  pubkey_authentication: yes

  # Expect .ssh/authorized_keys2 to be disregarded by default in future.
  authorized_keys_file:
    - .ssh/authorized_keys

  authorized_principals_file: none

  authorized_keys_command: none
  authorized_keys_command_user: nobody

  # For this to work you will also need host keys in /etc/ssh/ssh_known_hosts
  hostbased_authentication: no
  # Change to yes if you don't trust ~/.ssh/known_hosts for
  # HostbasedAuthentication
  ignore_user_known_hosts: no
  # Don't read the user's ~/.rhosts and ~/.shosts files
  ignore_rhosts: yes

  # To disable tunneled clear text passwords, change to no here!
  password_authentication: yes
  permit_empty_passwords: no

  # Change to yes to enable challenge-response passwords (beware issues with
  # some PAM modules and threads)
  challenge_response_authentication: no

  # Kerberos options
  kerberos_authentication: no
  kerberos_or_local_passwd: yes
  kerberos_ticket_cleanup: yes
  kerberos_get_afs_token: no

  # GSSAPI options
  gss_api_authentication: no
  gss_api_cleanup_credentials: yes
  gss_api_strict_acceptor_check: yes
  gss_api_key_exchange: no

  # Set this to 'yes' to enable PAM authentication, account processing,
  # and session processing. If this is enabled, PAM authentication will
  # be allowed through the ChallengeResponseAuthentication and
  # PasswordAuthentication.  Depending on your PAM configuration,
  # PAM authentication via ChallengeResponseAuthentication may bypass
  # the setting of "PermitRootLogin without-password".
  # If you just want the PAM account and session checks to run without
  # PAM authentication, then enable this but set PasswordAuthentication
  # and ChallengeResponseAuthentication to 'no'.
  use_pam: yes

  allow_agent_forwarding: yes
  allow_tcp_forwarding: yes
  gateway_ports: no
  x11_forwarding: no
  x11_display_offset: 10
  x11_use_localhost: yes
  permit_tty: yes
  print_motd: no
  print_last_log: yes
  tcp_keep_alive: yes
  permituser_environment: no
  compression: delayed
  client_alive_interval: 0
  client_alive_count_max: 3
  use_dns: no
  pid_file: /var/run/sshd.pid
  max_startups: 10:30:100
  permit_tunnel: no
  chroot_directory: none
  version_addendum: none

  # no default banner path
  banner: none

  # Allow client to pass locale environment variables
  accept_env:
    - LANG
    - LC_*

  # override default of no subsystems
  subsystem:
    - name: sftp
      path: /usr/lib/openssh/sftp-server

  # Example of overriding settings on a per-user basis
  match_users:
    - username: anoncvs
      options:
        - X11Forwarding: no
        - AllowTcpForwarding: no
        - PermitTTY: no
        - ForceCommand:
            - cvs
            - server

ssh_defaults_config:
  - host: "*"
    # ForwardAgent: false
    # ForwardX11: false
    # ForwardX11Trusted: false
    # PasswordAuthentication: true
    # HostbasedAuthentication: ""
    # GSSAPIAuthentication: ""
    # GSSAPIDelegateCredentials: ""
    # GSSAPIKeyExchange: false
    # GSSAPITrustDNS: false
    # BatchMode: false
    # CheckHostIP: true
    # AddressFamily: any
    # ConnectTimeout: 0
    # StrictHostKeyChecking: ask
    # IdentityFile:
    #   - "~/.ssh/id_rsa"
    #   - "~/.ssh/id_dsa"
    #   - "~/.ssh/id_ecdsa"
    #   - "~/.ssh/id_ed25519"
    # Port: 22
    # Ciphers:
    #   - aes128-ctr
    #   - aes192-ctr
    #   - aes256-ctr
    #   - aes128-cbc
    #   - 3des-cbc
    # MACs:
    #   - hmac-md5
    #   - hmac-sha1
    #   - umac-64@openssh.com
    # EscapeChar: "~"
    # Tunnel: false
    # TunnelDevice: "any:any"
    # PermitLocalCommand: false
    # VisualHostKey: false
    # ProxyCommand: ssh -q -W %h:%p gateway.example.com
    # RekeyLimit: 1G 1h
    # UserKnownHostsFile: ~/.ssh/known_hosts.d/%k
    SendEnv:
      - "LANG LC_*"
    HashKnownHosts: true

...
