
role_name_check: 1

dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: instance
    image: "ghcr.io/bodsch/docker-ansible/ansible-${DISTRIBUTION:-debian:12}"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    docker_host: "${DOCKER_HOST:-unix://run/docker.sock}"
    privileged: true
    pre_build_image: true
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - /var/lib/containerd
    capabilities:
      - SYS_ADMIN
    tmpfs:
      - /run
      - /tmp
    groups:
      - syslog
      - syslog_server
    docker_networks:
      - name: syslog
        ipam_config:
          - subnet: "10.19.0.0/24"
            gateway: "10.19.0.2"
    networks:
      - name: syslog
        ipv4_address: "10.19.0.10"

  - name: client_1
    image: "ghcr.io/bodsch/docker-ansible/ansible-${DISTRIBUTION:-debian:12}"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    docker_host: "${DOCKER_HOST:-unix://run/docker.sock}"
    privileged: true
    pre_build_image: true
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - /var/lib/containerd
    capabilities:
      - SYS_ADMIN
    tmpfs:
      - /run
      - /tmp
    groups:
      - syslog
      - syslog_client
    networks:
      - name: syslog
        ipv4_address: "10.19.0.21"

  - name: client_2
    image: "ghcr.io/bodsch/docker-ansible/ansible-${DISTRIBUTION:-debian:12}"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    docker_host: "${DOCKER_HOST:-unix://run/docker.sock}"
    privileged: true
    pre_build_image: true
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - /var/lib/containerd
    capabilities:
      - SYS_ADMIN
    tmpfs:
      - /run
      - /tmp
    groups:
      - syslog
      - syslog_client
    networks:
      - name: syslog
        ipv4_address: "10.19.0.22"


provisioner:
  name: ansible
  ansible_args:
    - --diff
    - -v
  config_options:
    defaults:
      deprecation_warnings: true
      stdout_callback: yaml
      gathering: smart
      fact_caching_timeout: 320
scenario:
  test_sequence:
    - destroy
    - dependency
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - destroy
verifier:
  name: testinfra
