---
galaxy_info:
  role_name: sshd

  author: Bodo Schulz
  description: Manage sshd configuration
  license: Apache

  min_ansible_version: "2.10"
  platforms:
    - name: ArchLinux
    - name: Debian
      versions:
        # 10
        - buster
        - bullseye
    - name: Ubuntu
      versions:
        # 20.04
        - focal

  galaxy_tags:
    - system
    - sshd

dependencies: []
