---

- name: create certificate
  delegate_to: localhost
  become: false
  run_once: true

  block:

    - name: check for archive {{ snakeoil_domain }}_{{ current_date }}.tgz on ansible controller
      ansible.builtin.stat:
        path: "{{ snakeoil_local_tmp_directory }}/{{ snakeoil_domain }}_{{ current_date }}.tgz"
      register: _certificate_archive_local

    - name: define checksum for {{ snakeoil_domain }} on ansible controller
      ansible.builtin.stat:
        path: "{{ snakeoil_local_tmp_directory }}/{{ snakeoil_domain }}_{{ current_date }}.tgz"
        get_checksum: false
        get_mime: false
        get_attributes: false
      register: _certificate_archive_checksum_local
      when:
        - _certificate_archive_local is defined
        - _certificate_archive_local.stat is defined
        - _certificate_archive_local.stat.exists | default('true')

    - name: set facts
      ansible.builtin.set_fact:
        snakeoil_certificate_archive_checksum_local: "{{ _certificate_archive_checksum_local.stat.checksum | default('+') }}"

    - name: create archive
      when:
        - snakeoil_certificate_archive_checksum_local != snakeoil_certificate_archive_checksum_remote
      block:
        - name: compress directory for {{ snakeoil_domain }}
          community.general.archive:
            path: "{{ snakeoil_local_tmp_directory }}/{{ snakeoil_domain }}"
            dest: "{{ snakeoil_local_tmp_directory }}/{{ snakeoil_domain }}_{{ current_date }}.tgz"
            mode: 0600
