---

sshd_config:
  address_family: inet
  listen_address:
    - "{{ ansible_default_ipv4.address }}:2222"
    - "0.0.0.0:22"

  log_level: VERBOSE
  syslog_facility: AUTHPRIV
  login_grace_time: 2m
  max_auth_tries: 3
  max_sessions: 10
  pubkey_authentication: true
  password_authentication: false
  authorized_keys_file:
    - "/etc/ssh/authorized_keys/%u"
    - ".ssh/authorized_keys"
  UseDNS: false
  client_alive_interval: 60
  client_alive_count_max: 3
  print_last_log: true
  accept_env:
    - COLORTERM
    - LANG
    - LANGUAGE
    - LC_CTYPE
    - LC_NUMERIC
    - LC_TIME
    - LC_COLLATE
    - LC_MESSAGES
    - LC_MEASUREMENT
    - LC_ALL

...
