---

sshd_config:
  #Port: 22
  #address_family: inet
  listen_address:
    - "{{ ansible_default_ipv4.address }}:2222"
    - "0.0.0.0:22"
  log_level: INFO
  syslog_facility: AUTHPRIV
  login_grace_time: 2m
  max_auth_tries: 3
  max_sessions: 10
  pubkey_authentication: true
  password_authentication: false
  authorized_keys_file:
    - "/etc/ssh/authorized_keys/%u"
    - ".ssh/authorized_keys"
  UseDNS: false
  client_alive_interval: 60
  client_alive_count_max: 3
  print_last_log: true
  accept_env:
    - COLORTERM
    - LANG
    - LANGUAGE
    - LC_*
  Ciphers:
    - aes256-cbc
    - aes192-cbc
    - aes128-cbc,3des-cbc
  host_key_algorithms:
    - ssh-ed25519
    - ssh-ed25519-cert-v01@openssh.com
    - rsa-sha2-512
  kex_algorithms:
    - diffie-hellman-group-exchange-sha256
    - diffie-hellman-group-exchange-sha1
    - diffie-hellman-group14-sha1
  MACs:
    - hmac-sha2-256
    - hmac-sha1

  subsystem:
    name: sftp
    path: /usr/lib/openssh/sftp-server

  # Example of overriding settings on a per-user basis
  match_users:
    - username: anoncvs
      options:
        x11_forwarding: false
        AllowTcpForwarding: false
        PermitTTY: false
        ForceCommand:
          - cvs
          - server

...
