#!/usr/bin/env bash

. hooks/_tox_base

echo "install collection ${COLLECTION_NAMESPACE}.${COLLECTION_NAME} to ${COLLECTION_DIR}"

mkdir \
  --parents \
  "${COLLECTION_DIR}"

rsync \
  --archive \
  --verbose \
  --recursive \
  --exclude hooks \
  --exclude __pycache__ \
  --delete \
  ../ansible-collection-$COLLECTION_NAME/* \
  "${COLLECTION_DIR}/"
