---
- name: reload systemctl daemon
  ansible.builtin.systemd:
    daemon_reload: true
  when:
    - ansible_service_mgr == 'systemd'

- name: reload syslog-ng
  ansible.builtin.service:
    name: '{{ syslog_unit_file }}'
    state: reloaded
  when:
    - not ansible_check_mode

- name: restart syslog-ng
  ansible.builtin.service:
    name: '{{ syslog_unit_file }}'
    state: restarted
  when:
    - not ansible_check_mode

- name: validate syslog-ng config
  bodsch.core.syslog_cmd:
    parameters:
      - --syntax-only
  check_mode: true
  when:
    - not ansible_check_mode

- name: restart systemd-journald
  ansible.builtin.service:
    name: systemd-journald
    state: restarted

- name: wait for clean startup
  ansible.builtin.pause:
    seconds: 5
