---

# server or client
openvpn_type: "server"

openvpn_systemd:
  requires_services:
    - sshd.service

openvpn_logging:
  verbosity: 4

openvpn_easyrsa: {}

openvpn_certificate:
  req_country: USA
  req_province: Hamilton
  req_city: Eastvilage

openvpn_server:
  # external IP of VPN server (EIP)
  external_ip: "{{ ansible_default_ipv4.address | default(ansible_all_ipv4_addresses[0]) }}"

openvpn_config_save_dir: ""

openvpn_subnet:
  ip: 10.8.3.0
  mask: 255.255.255.0

...
