---

- name: merge sshd configuration between defaults and custom
  ansible.builtin.set_fact:
    ssh_config: "{{ ssh_defaults_config | bodsch.core.merge_lists(ssh_config) | bodsch.core.sshd_values }}"
    sshd_config: "{{ sshd_defaults_config | combine(sshd_config, recursive=True) | bodsch.core.sshd_values }}"
  tags:
    - sshd
    - configuration

# - name: check FIPS mode
#   when:
#     - sshd_hostkeys_nofips | default([])
#   block:
#     - name: check the kernel FIPS mode
#       ansible.builtin.slurp:
#         src: /proc/sys/crypto/fips_enabled
#       register: sshd_kernel_fips_mode
#       failed_when: false
#
#     - name: check the userspace FIPS mode
#       ansible.builtin.slurp:
#         src: /etc/system-fips
#       register: sshd_userspace_fips_mode
#       failed_when: false

- name: create /etc/ssh/sshd_config.d
  ansible.builtin.file:
    state: directory
    name: /etc/ssh/sshd_config.d
    mode: "0750"
  tags:
    - sshd
    - configuration

- name: create /etc/ssh/ssh_config.d
  ansible.builtin.file:
    state: directory
    name: /etc/ssh/ssh_config.d
    mode: "0750"
  tags:
    - sshd
    - configuration

- name: configure ssh_config
  ansible.builtin.template:
    src: sshd/ssh_config.j2
    dest: /etc/ssh/ssh_config
    mode: "0644"
    backup: true
  tags:
    - sshd
    - configuration

- name: create overriding settings on a per-user basis
  ansible.builtin.template:
    src: sshd/sshd_config.d/match_users.conf.j2
    dest: /etc/ssh/sshd_config.d/match_users.conf
    mode: "0644"
    backup: true
    validate: "{{ sshd_binary }} -t -f %s"
  notify:
    - restart sshd
  tags:
    - sshd
    - configuration

- name: create subsystem configuration
  ansible.builtin.template:
    src: sshd/sshd_config.d/subsystem.conf.j2
    dest: /etc/ssh/sshd_config.d/subsystem.conf
    mode: "0644"
    backup: true
    validate: "{{ sshd_binary }} -t -f %s"
  notify:
    - restart sshd
  tags:
    - sshd
    - configuration

- name: configure sshd.conf
  ansible.builtin.template:
    src: sshd/sshd_config.j2
    dest: /etc/ssh/sshd_config
    mode: "0644"
    backup: true
    validate: "{{ sshd_binary }} -t -f %s"
  notify:
    - restart sshd
  tags:
    - sshd
    - configuration
