---

- name: create openvpn log directory
  ansible.builtin.file:
    state: directory
    path: '{{ openvpn_logging.directory }}'
    owner: "{{ openvpn_owner }}"
    group: "{{ openvpn_group }}"
    mode: "0775"
  tags:
    - setup
    - openvpn

- name: create client key directory
  ansible.builtin.file:
    state: directory
    path: '{{ openvpn_directory }}/keys'
    owner: "{{ openvpn_owner }}"
    group: "{{ openvpn_group }}"
    mode: "0755"
  tags:
    - setup
    - openvpn

- name: create a combined client list
  become: false
  delegate_to: localhost
  run_once: true
  ansible.builtin.set_fact:
    openvpn_client_list: "{{ openvpn_client_list | default([]) | bodsch.core.openvpn_clients(hostvars[item]) }}"
  loop: "{{ ansible_play_hosts }}"
  loop_control:
    loop_var: item
  no_log: true

- name: configure openvpn server
  ansible.builtin.include_tasks: configure/server.yml
  when:
    - openvpn_type == "server"

- name: configure openvpn client
  ansible.builtin.include_tasks: configure/client.yml
  when:
    - openvpn_mobile_clients is defined
    - openvpn_mobile_clients | count > 0

# - name: change rights for created files
#   ansible.builtin.file:
#     state: directory
#     path: "{{ openvpn_directory }}/keys"
#     owner: "{{ openvpn_owner }}"
#     group: "{{ openvpn_group }}"
#     recurse: true

...
